## 09/21 mml.pdf Vector Calculus Chapter 5 and exercises from chapter 4 137 page 

Linear regression  
2D plot, many data points,  
1. Draw a line
2. Calculate the squared distance of every point to a line
3. Change the line a little
4. Go to 2. until all lines are drown
5. Now plot the sum of squared distances (SS) for every line
6. The one with the smallest values of SS distances is our fit
7. SS(fit) := a sum of squared distances from the data points to our best fit line
8. Variance of fit or Var(fit) = SS(fit)/n, where n is the number of data points
9. Take an axis that we want to predict based on the data, say z
10. Calculate sum of squared distances of every z component to the mean of all z, or SS(mean)
11. SS(mean) sum of squared distance of every z component to the mean z
12. Var(mean) = SS(mean)/n, -> the average squared distance to z mean per mouse
13. Var(mean) how z varies per mouse
14. Var(fit) can be seen as a variation of z (f.e. tail size of a mouse) according to the fit line
15. So if we fit the tail sizes with respect to the weight of a mouse then we get the fit line.
16. In this way Var(fit) is the variation of tail sizes when we ajusted to the weight factor.
17. So Vat(mean)-Var(fit) is how much of variation is explained by weight 
18. if we divide Vat(mean)-Var(fit) by Var(mean) the reduction of varience due to weight ajustment
19. Var was Var(mean) before but after fitting to a line w.r.t. weight we the var changed to Var(fit)
20. So delta(Var)/Var(mean) is how much varience reduced due to the introduction of weight

p-value determines how reliable the data is -- the smaller the better/more reliable
R^2 determines how our varience was reduced due to the introduction of new parameters
the more R^2 the better z is explained by introduced parameters


### Solving/finding SVD for a matrix ("2 2; -1 1")

In [49]:
import numpy as np
A = np.matrix("2 2; -1 1")
AT= A.transpose()

AAT=A@AT
ATA=AT@A


val1, V = np.linalg.eig(ATA)

print("ATA = V * sigma square * VT")
print(ATA)

print("V", V)
print("eigenvaluse", np.diag(val1))

val2, U = np.linalg.eig(AAT)
print("AAT = U * sigma square * UT")
print(AAT)

print("U", U)
print("eigenvaluse", np.diag(val2))

import math
S = [math.sqrt(x) for x in val2]
S = np.diag(S)
print(S)

U@S@V.transpose()

ATA = V * sigma square * VT
[[5 3]
 [3 5]]
V [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
eigenvaluse [[8. 0.]
 [0. 2.]]
AAT = U * sigma square * UT
[[8 0]
 [0 2]]
U [[1. 0.]
 [0. 1.]]
eigenvaluse [[8. 0.]
 [0. 2.]]
[[2.82842712 0.        ]
 [0.         1.41421356]]


matrix([[ 2.,  2.],
        [-1.,  1.]])

In [52]:
math.exp(2)

7.38905609893065